account:
    login: fuckmail@voila.fr
    password: azerty
    esn: Plopido
    email: fuckmail@voila.fr

modules:
    everytime:
        - \Jhiino\ESNLeJeu\Module\StatsModule: popularity
        - \Jhiino\ESNLeJeu\Module\StatsModule: tenders
    audit:
        - \Jhiino\ESNLeJeu\Module\AuditModule: fireEmployees
        - \Jhiino\ESNLeJeu\Module\AuditModule: renegotiateContracts
    flannel:
        - \Jhiino\ESNLeJeu\Module\ComplaintsModule: flannel
    business:
        - \Jhiino\ESNLeJeu\Module\TendersModule: bidOnTenders

tenders:
    hire: true
    min_weeks: 4
    min_interest_margin: 0.21
    trade_promotion: 0.99
    max_bid_per_hour: 15

employees:
    hire_employees: true
    hire_freelances: false

audit:
    fire: false
    max_fire_per_hour: 300
    renegotiate_contracts: true
    renegotiate_type:
        very_good: true
        good: true
        bad: true
        very_bad: true
    break_type:
        very_good: false
        good: false
        bad: false
        very_bad: false

mailer:
    host: smtp.gmail.com
    port: 465
    security: ssl
    username: thomas.sieffert
    password: qwgcwprdbrxyksdt
    from: thomas.sieffert@gmail.com
    from_as: ESN Le Bot - Plopido
    recipients:
        - caporaldead@gmail.com

logger:
    levels: [ EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO ] # DEBUG

development:
    activate: false
